version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: .Dockerfile-mysql
    environment:
      MYSQL_DATABASE: shubham
      MYSQL_USER: shubham
      MYSQL_PASSWORD: Shubham123!
      MYSQL_ROOT_PASSWORD: Shubham123!
    ports:
      - "3306:3306"
    networks:
      - my-network

  node-1:
    build:
      context: .
      dockerfile: .Dockerfile-node
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: shubham
      DB_PASSWORD: Shubham123!
      DB_DATABASE: shubham
    depends_on:
      - mysql
    networks:
      - my-network

  node-2:
    build:
      context: .
      dockerfile: .Dockerfile-node
    ports:
      - "3001:3000"  # Different port for node-2 service, exposed as 3001 on the host
    environment:
      DB_HOST: mysql
      DB_USER: shubham
      DB_PASSWORD: Shubham123!
      DB_DATABASE: shubham
    depends_on:
      - mysql
    networks:
      - my-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the custom Nginx config
    depends_on:
      - node-1
      - node-2
    networks:
      - my-network

networks:
  my-network:
    driver: bridge