apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-1
  template:
    metadata:
      labels:
        app: node-1
    spec:
      containers:
      - name: node
        image: node
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_PASSWORD
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE